# This is a basic workflow to help you get started with Actions

name: deploy-xiaoyuBlog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.1.0
        with: 
          node-version: "16.X"
      - name: install deps
        run: npm install
      - name: npm run build
        run: npm run build
      - name: copy files with scp
        uses: appleboy/scp-action@v0.0.1
        with: 
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          port: 22
          source: 'articles/  .next/  next.config.js package.json  yarn.lock'
          target: ${{ secrets.REMOTE_TARGET }}
      
        


